name: workflow

on:
  push:
  schedule:
    - cron: '0 0 1 * *'  # run once-a-month

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: conda-environment
        environment-file: binder/environment.yml

    - name: Install testing packages
      run: python -m pip install --upgrade pip nbval

    - name: Jupyter notebook tests
      run: python -m pytest -v --nbval-lax notebooks/*.ipynb
